### PR TITLE
Updated noTone.asdoc to german.

### PR DESCRIPTION
**Pull request by SeppPenner**
See https://github.com/arduino/reference-de/issues/11

### CODE REVIEW

**Comment by SeppPenner** [comment]
@smellai I don't have to or I mustn't? ❓  I mean, it's not really a big deal to translate that, too.

**Comment by SeppPenner** [comment]
Thanks for the invitation by the way, this makes the collaboration a bit more easy.

**Comment by smellai** [comment]
you mustn't ;)

**Comment by SeppPenner** [comment]
Am I allowed to merge this on my own or does anyone want to take a look over this (Specially if the styling is correct)? Otherwise I would just provide commits on a working branch of this repository and put them back to the master whenever it makes sense (E.g. when a folder is finished or so)

**Pull request merged**
